#!/usr/bin/python3
"""Module that factorize as many numbers as possible
 into a product of two smaller numbers."""
from sys import argv


def factorize(breezy):
    """"print a simple descomposition of an integer > 1"""
    i = 2

    if breezy < 2:
        return
    print()
    while breezy % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(breezy, breezy / i, i), end="")
if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            breezy = int(line.split('\n')[0])
            factorize(breezy)
            line = file.readline()
except:
    pass
